version: "3"
services:
  database:
    container_name: vscode-database
    image: postgres:latest
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - traefik_default
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      POSTGRES_DB: vscode-server-tool
    tty: true
  frontend:
    build: .
    depends_on:
      database:
        condition: service_healthy
    networks:
      - traefik_default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./git-repos:/app/git-repos
    environment:
      - HOST=${HOST:-localhost}
      - PORT=80
      - DATABASE_URL=postgres://${DATABASE_USER:-postgres}:${DATABASE_PASSWORD:-postgres}@vscode-database:5432/vscode-server-tool
      - SESSION_SECRET=${SESSION_SECRET:-my-secret}
      # Note that the PWD Environment variable doesn't exist on windows, so you'll have to assign the PWD the absolute path to this repository in the .env file
      - GIT_FOLDER_MOUNT=${PWD}/git-repos
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${HOST:-localhost}`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.routers.frontend.priority=1"
  traefik:
    image: traefik:v2.6
    ports:
      - "80:80"
    networks:
      - traefik_default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=traefik_default
      - --entrypoints.web.address=:80

networks:
  traefik_default:
