version: "2.1"
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vscode-server-tool
    tty: true
  traefik:
    image: traefik:v2.6
    ports:
      - "3030:3030"
      - "8080:8080"
    networks:
      - traefik_default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --api.debug=true
      - --log.level=DEBUG
      - --api.insecure=true
      - --api.dashboard=true

      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=traefik_default
      - --entrypoints.web.address=:3030

networks:
  traefik_default:
