version: "3"
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vscode-server-tool
    tty: true
  traefik:
    image: traefik:v2.6
    ports:
      - "80:80"
      - "80085:80085"
    networks:
      - traefik_default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=traefik_default
      - --entrypoints.web.address=:80
      - --entrypoints.servers.address=:80085
  frontend:
    build: .
    networks:
      - traefik_default
    environment:
      - HOST=localhost
      - GIT_FOLDER=git-repos
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.entrypoints=web"

networks:
  traefik_default:
